In [86]:
versioninfo()

Julia Version 1.0.3
Commit 099e826241 (2018-12-18 01:34 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, broadwell)
Environment:
  JULIABOX = true
  JULIA_PKG_SERVER = https://pkg.juliacomputing.com
  JULIA = /opt/julia-0.6/bin/julia
  JULIA_KERNELS = ['julia-0.6', 'julia-1.0', 'julia-1.0k']
  JULIA_PKG_TOKEN_PATH = /mnt/juliabox/.julia/token.toml
  JULIABOX_ROLE = 


# COLLECTIONS

* Collections are groups of elements
* Elements are values of different Julia data types
* Storing elements in collections is one of the most useful operations in computing

## I ARRAYS

*  Arrays are collections of values separated with commas and placing them inside of square brackets
* They are represented in column or in row form

In [1]:
# 1 A column vector
array1 = [1, 2, 3]
typeof(array1)

Array{Int64,1}

In [3]:
array1

3-element Array{Int64,1}:
 1
 2
 3

In [2]:
# 2 A row vector
array2 = [1 2 3]
typeof(array2)

Array{Int64,2}

In [4]:
array2

1×3 Array{Int64,2}:
 1  2  3

In [5]:
# 3 The transpose converts between the two
transpose(array1)
#The apostrophe is an alternative notation
array1'

1×3 LinearAlgebra.Adjoint{Int64,Array{Int64,1}}:
 1  2  3

In [6]:
# 4 Boolean logic (==)
transpose(array1) == array1'

true

In [7]:
# 5 Data type inheritance
# With a mix of types, all the elements inherent the "highest" type
array2 = [1, 2, 3.0]
#Index for one of the original integers will be Float64
array2[1]

1.0

In [8]:
# 6 Column-wise entry of multidimensional array
array3 = [[1, 2, 3] [4, 5, 6] [7, 8, 9]]

3×3 Array{Int64,2}:
 1  4  7
 2  5  8
 3  6  9

In [9]:
# 7 Row-wise entry of multidimensional array
array4 = [[1 2 3]; [4 5 6]; [7 8 9]]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [11]:
# 8 Length of array
length(array3)

9

In [12]:
length(array4)

9

In [13]:
# 9 Index order of column-wise array
for i in 1:length(array3)
    println("Element $(i) is ", array3[i])
end

Element 1 is 1
Element 2 is 2
Element 3 is 3
Element 4 is 4
Element 5 is 5
Element 6 is 6
Element 7 is 7
Element 8 is 8
Element 9 is 9


In [14]:
# 10 Index order of row-wise array
for i in 1:length(array4)
    println("Element $(i) is ", array4[i])
end

Element 1 is 1
Element 2 is 4
Element 3 is 7
Element 4 is 2
Element 5 is 5
Element 6 is 8
Element 7 is 3
Element 8 is 6
Element 9 is 9


In [15]:
# 11 Using repeat() to repeat elements
repeat([1, 2], 3)

6-element Array{Int64,1}:
 1
 2
 1
 2
 1
 2

In [17]:
# 12 Using range(start, step, number of elements)
range(1, step = 1, length = 10)

1:1:10

In [18]:
typeof(range(1, step = 1, length = 10))

StepRange{Int64,Int64}

In [19]:
# 13 Create collections usin gthe collect() function
collect(range(1, step = 1, length = 10))

10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [20]:
#Short-hand
collect(1:10)

10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [21]:
typeof(1:10)

UnitRange{Int64}

In [22]:
#Add step size
collect(2:2:10)

5-element Array{Int64,1}:
  2
  4
  6
  8
 10

In [23]:
typeof(collect(2:2:10))

Array{Int64,1}

In [24]:
# 14 Creating empty array with two rows and three columns
array5 = Array{Union{Missing, Int}}(missing, 2, 3)

2×3 Array{Union{Missing, Int64},2}:
 missing  missing  missing
 missing  missing  missing

In [25]:
# 15 Reshaping
reshape(array5, 3, 2)

3×2 Array{Union{Missing, Int64},2}:
 missing  missing
 missing  missing
 missing  missing

In [26]:
# 16 Indexing (slicing)
#Random uniform distribution of values in closed domain [10,20]
#Shape 10 x 5
array6 = rand(10:20, 10, 5)

10×5 Array{Int64,2}:
 16  19  19  15  15
 16  12  19  10  18
 20  18  19  17  13
 16  17  20  15  17
 13  15  10  14  19
 20  15  18  14  18
 12  10  13  16  10
 20  18  11  18  14
 17  19  12  10  14
 11  14  10  15  19

In [27]:
#All rows in first column
array6[:, 1]

10-element Array{Int64,1}:
 16
 16
 20
 16
 13
 20
 12
 20
 17
 11

In [28]:
#Rows two through five of second column
array6[2:5, 2]

4-element Array{Int64,1}:
 12
 18
 17
 15

In [29]:
#Values in rows 2, 4, 6, and in columns 1 and 5
array6[[2, 4, 6], [1, 5]]

3×2 Array{Int64,2}:
 16  18
 16  17
 20  18

In [30]:
#Values in row 1 from column 3 to the last column
array6[1, 3:end]

3-element Array{Int64,1}:
 19
 15
 15

In [31]:
# Boolean logic (returning only true and false)
array6[:, 1] .> 12

10-element BitArray{1}:
  true
  true
  true
  true
  true
  true
 false
  true
  true
 false

In [32]:
# 17 Changing element values
array7 = [1, 2, 3, 4, 5]

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [33]:
#Permanantly append 10 to end of array
push!(array7, 10)

6-element Array{Int64,1}:
  1
  2
  3
  4
  5
 10

In [34]:
#Remove last element
#Only the removed value will be displayed
pop!(array7)
array7

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [35]:
#Change second element value to 1000
array7[2] = 1000
array7

5-element Array{Int64,1}:
    1
 1000
    3
    4
    5

In [36]:
# 18 List comprehension
array8 = [3 * i for i in 1:5]

5-element Array{Int64,1}:
  3
  6
  9
 12
 15

In [37]:
#Column-wise collection iterating through second element first
array9 = [a * b for a in 1:3, b in 1:3]

3×3 Array{Int64,2}:
 1  2  3
 2  4  6
 3  6  9

In [38]:
# 19 Arithmetic on arrays
#Elementwise addition of a scalar using dot notation
array8 .+ 1

5-element Array{Int64,1}:
  4
  7
 10
 13
 16

In [39]:
#Elementwise addition of similar sized arrays
array7 + array8

5-element Array{Int64,1}:
    4
 1006
   12
   16
   20

* `Missing` is a Julia data type
* Provides a placeholder for missing data in a statistical sense
* Propagates automatically
* Equality as a type can be tested
* Sorting is possible since missing is seen as greater than other values

In [40]:
#20 Missing values
#Propagation
missing + 1

missing

In [41]:
missing > 1

missing

In [42]:
[1, 2, 3, missing, 5] + [10, 20, 30, 40 ,50]

5-element Array{Union{Missing, Int64},1}:
 11       
 22       
 33       
   missing
 55       

In [43]:
#Cannot return true or false since value is not known
missing == missing

missing

In [44]:
#Equality
missing === missing

true

In [45]:
isequal(missing, missing)

true

In [46]:
#Sorting with isless()
isless(1, missing)

true

In [47]:
isless(Inf, missing)

true

In [48]:
# 21 Array of integer zeros
array11 = zeros(Int8, 3, 3)

3×3 Array{Int8,2}:
 0  0  0
 0  0  0
 0  0  0

In [49]:
# 22 Array of floating point ones
array12 = ones(Float16, 3, 3)

3×3 Array{Float16,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [50]:
# 23 Array of true (bit array) values
array13 = trues(3, 3)

3×3 BitArray{2}:
 true  true  true
 true  true  true
 true  true  true

In [51]:
# 24 Fill an array with n elements of value x
array14 = fill(10, 3, 3)

3×3 Array{Int64,2}:
 10  10  10
 10  10  10
 10  10  10

In [52]:
# 25 Convert elements to a different data type
convert.(Float16, array14)

3×3 Array{Float16,2}:
 10.0  10.0  10.0
 10.0  10.0  10.0
 10.0  10.0  10.0

In [53]:
# 26 Concatenation
#Concatenate arrays along rows (makes row)
array15 = [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [54]:
array16 = [10, 20, 30]

3-element Array{Int64,1}:
 10
 20
 30

In [55]:
cat(array15, array16, dims = 1)

6-element Array{Int64,1}:
  1
  2
  3
 10
 20
 30

In [56]:
#Same as above
vcat(array15, array16)

6-element Array{Int64,1}:
  1
  2
  3
 10
 20
 30

In [57]:
#Concatenate arrays along columns (makes colums)
cat(array15, array16, dims = 2)

3×2 Array{Int64,2}:
 1  10
 2  20
 3  30

In [58]:
#Same as above
hcat(array15, array16)

3×2 Array{Int64,2}:
 1  10
 2  20
 3  30

## II Tuples

* Tuples are immutable collections

In [59]:
# 1 Tuples with mixed types
tuple1 = (1, 2, 3, 4, "Julia")

(1, 2, 3, 4, "Julia")

In [60]:
#For loop to look at value and type of each element
for i in 1:length(tuple1)
    println(" The value of the tuple at index number $(i) is $(tuple1[i]) and the type is $(typeof(tuple1[i])).")
end

 The value of the tuple at index number 1 is 1 and the type is Int64.
 The value of the tuple at index number 2 is 2 and the type is Int64.
 The value of the tuple at index number 3 is 3 and the type is Int64.
 The value of the tuple at index number 4 is 4 and the type is Int64.
 The value of the tuple at index number 5 is Julia and the type is String.


In [61]:
# 2 Each element can be named
a, b, c, seven = (1, 3, 5, 7)

(1, 3, 5, 7)

In [62]:
a

1

In [63]:
seven

7

In [64]:
# 2 Reverse order index (can be done with arrays too)
tuple1[end:-1:1]

("Julia", 4, 3, 2, 1)

In [65]:
# 3 Mixed length tuples
tuple2 = ((1, 2, 3), 1, 2, (3, 100, 1))

((1, 2, 3), 1, 2, (3, 100, 1))

In [66]:
#Element 4
tuple2[4]

(3, 100, 1)

In [67]:
#Element 2 in element 4
tuple2[4][2]

100

## III DICTIONARIES

* Dictionaries are collections of key-value pairs

In [68]:
# 1 Example of a dictionary
dictionary1 = Dict(1 => 77, 2 => 66, 3 => 1)

Dict{Int64,Int64} with 3 entries:
  2 => 66
  3 => 1
  1 => 77

In [69]:
#The => is shorthand for the Pair() function
dictionary2 = Dict(Pair(1,100), Pair(2,200), Pair(3,300))

Dict{Int64,Int64} with 3 entries:
  2 => 200
  3 => 300
  1 => 100

In [70]:
# 2 Specifying types
dictionary3 = Dict{Any, Any}(1 => 77, 2 => 66, 3 => "three")

Dict{Any,Any} with 3 entries:
  2 => 66
  3 => "three"
  1 => 77

In [71]:
#We can get a bit crazy
dictionary4 = Dict{Any, Any}("a" => 1, (2, 3) => "hello")

Dict{Any,Any} with 2 entries:
  (2, 3) => "hello"
  "a"    => 1

In [72]:
# 3 Using symbols as keys
dictionary5 = Dict(:A => 300, :B => 305, :C => 309)

Dict{Symbol,Int64} with 3 entries:
  :A => 300
  :B => 305
  :C => 309

In [73]:
dictionary5[:A]

300

In [74]:
# 4 Using in() to check on key-value pairs
in((:A => 300), dictionary5)

true

In [75]:
# 5 Changing an existing value
dictionary5[:C] = 1000

1000

In [76]:
dictionary5

Dict{Symbol,Int64} with 3 entries:
  :A => 300
  :B => 305
  :C => 1000

In [77]:
# 6 Using the delete!() function
delete!(dictionary5, :A)

Dict{Symbol,Int64} with 2 entries:
  :B => 305
  :C => 1000

In [78]:
# 7 The keys of a dictionary
keys(dictionary5)

Base.KeySet for a Dict{Symbol,Int64} with 2 entries. Keys:
  :B
  :C

In [79]:
# 8 The values of a dictionary
values(dictionary5)

Base.ValueIterator for a Dict{Symbol,Int64} with 2 entries. Values:
  305
  1000

In [80]:
# 8 Creating a dictionary with automatic keys
procedure_vals = ["Appendectomy", "Colectomy", "Cholecystectomy"]

3-element Array{String,1}:
 "Appendectomy"   
 "Colectomy"      
 "Cholecystectomy"

In [81]:
procedure_dict = Dict{AbstractString,AbstractString}()
for (s, n) in enumerate(procedure_vals)
    procedure_dict["x_$(s)"] = n
end

In [82]:
#Procedure_dict is now a dictionary
procedure_dict

Dict{AbstractString,AbstractString} with 3 entries:
  "x_1" => "Appendectomy"
  "x_2" => "Colectomy"
  "x_3" => "Cholecystectomy"

In [83]:
# 9 Iterating through a dictionary by key and value
for (k, v) in procedure_dict
    println(k, " is ",v)
end

x_1 is Appendectomy
x_2 is Colectomy
x_3 is Cholecystectomy


In [84]:
# 10 Sorting
dictionary6 = Dict("a"=> 1,"b"=>2 ,"c"=>3 ,"d"=>4 ,"e"=>5 ,"f"=>6)

Dict{String,Int64} with 6 entries:
  "f" => 6
  "c" => 3
  "e" => 5
  "b" => 2
  "a" => 1
  "d" => 4

In [85]:
# Sorting using a for loop
for k in sort(collect(keys(dictionary6)))
    println("$(k) is $(dictionary6[k])")
end

a is 1
b is 2
c is 3
d is 4
e is 5
f is 6
